spring:
 h2:
  console:
   enabled: true
   path: /h2
 datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb
  username: sa
  password:
 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    show_sql: false
    use_sql_comments: false
    format_sql: true
    dialect: org.hibernate.dialect.H2Dialect
    jdbc:
     lob.non_contextual_creation: true
work:
  jwtSecret: WorkSecretKey
  jwtExpiration: 86400     # 1 day
logging:
 file: app.log

info:
 app:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  encoding: '@project.build.sourceEncoding@'
  java:
   version:  '@java.version@'

